// Writes ASSETS.md: every audio / B-roll file the film expects, where it goes, and
// whether it exists yet. Doubles as the VO recording sheet. Run: npm run assets
import {existsSync, writeFileSync} from 'node:fs';
import {AUDIO_EXTENSIONS, MUSIC, SFX, voPath} from '../src/audio/library';
import {BROLL} from '../src/data/broll';
import {SCENES} from '../src/data/scenes';

const audioStatus = (base: string) => {
	const hit = AUDIO_EXTENSIONS.map((e) => base + e).find((p) => existsSync(`public/${p}`));
	return hit ? `✅ \`${hit}\`` : `⬜ \`${base}.mp3\``;
};
const fileStatus = (p: string) => (existsSync(`public/${p}`) ? `✅ \`${p}\`` : `⬜ \`${p}\``);

const lines: string[] = [];
lines.push('# Asset manifest', '');
lines.push('_Generated by `npm run assets` — do not edit by hand._', '');
lines.push('Drop files into `public/` at the paths below, then run `npm run sync:assets` (studio/render do this automatically).');
lines.push('Audio may be `.mp3`, `.wav`, `.m4a` or `.aac`. Missing files render as silent placeholders / labelled B-roll cards.', '');

lines.push('## Voiceover (one file per scene)', '');
lines.push('Scene lengths, subtitles, visual beats and SFX re-time automatically to the recorded duration.', '');
lines.push('| Scene | File | Line to record |', '|---|---|---|');
for (const s of SCENES.filter((x) => x.narration)) {
	lines.push(`| ${s.id} · ${s.title} | ${audioStatus(voPath(s.id))} | ${s.narration.replace(/\|/g, '\\|')} |`);
}

lines.push('', '## Music cues', '', '| Cue | File | Direction | Scenes |', '|---|---|---|---|');
for (const [id, m] of Object.entries(MUSIC)) {
	const scenes = SCENES.filter((s) => s.music === id).map((s) => s.id);
	lines.push(`| ${id} | ${audioStatus(m.path)} | ${m.name} | ${scenes[0]}–${scenes[scenes.length - 1]} |`);
}

lines.push('', '## Sound effects', '', '| ID | File | Sound | Uses |', '|---|---|---|---|');
for (const [id, sfx] of Object.entries(SFX)) {
	const uses = SCENES.reduce((n, s) => n + s.sfx.filter((c) => c.id === id).length, 0);
	lines.push(`| ${id} | ${audioStatus(sfx.path)} | ${sfx.name} | ${uses} |`);
}

lines.push('', '## B-roll & images', '', '| Shot | File | Description | Note |', '|---|---|---|---|');
for (const b of Object.values(BROLL)) {
	lines.push(`| ${b.shotId} | ${fileStatus(b.src)} | ${b.description} | ${'sourceNote' in b ? b.sourceNote : 'Royalty-free stock or original footage'} |`);
}
lines.push('');

writeFileSync('ASSETS.md', lines.join('\n'));
console.log('Wrote ASSETS.md');
