// Scans public/ and writes src/assets/available.generated.ts so the video
// only mounts <Audio>/<Img>/<OffthreadVideo> for files that actually exist.
// Everything else renders as a labelled placeholder. Runs before studio/render.
import {readdirSync, statSync, writeFileSync} from 'node:fs';
import {join, relative, sep} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const publicDir = join(root, 'public');
const MEDIA = /\.(mp3|wav|m4a|aac|ogg|mp4|mov|webm|png|jpe?g|webp)$/i;

const walk = (dir) =>
	readdirSync(dir).flatMap((name) => {
		const full = join(dir, name);
		return statSync(full).isDirectory() ? walk(full) : [full];
	});

const files = walk(publicDir)
	.filter((f) => MEDIA.test(f))
	.map((f) => relative(publicDir, f).split(sep).join('/'))
	.sort();

const out = `// AUTO-GENERATED by scripts/sync-assets.mjs — do not edit by hand.
export const AVAILABLE_ASSETS: readonly string[] = ${JSON.stringify(files, null, '\t')};
`;
writeFileSync(join(root, 'src/assets/available.generated.ts'), out);
console.log(`[sync-assets] ${files.length} media file(s) found in public/`);
